-- AlterTable
ALTER TABLE "categories" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT,
ALTER COLUMN "thumbnail_image" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "proOptions" ALTER COLUMN "color" SET DATA TYPE TEXT,
ALTER COLUMN "size" SET DATA TYPE TEXT,
ALTER COLUMN "images" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT,
ALTER COLUMN "detail" SET DATA TYPE TEXT;
