import { Role } from ".prisma/client";

// Customer Data (10)
export const customers = [
  {
    fullname: "Devonna Gohn",
    email: "dgohn0@gravatar.com",
    password: "oQqupSqQ7J6Z",
    shippingAddress: "56 Mcguire Court",
    phone: "868-457-3515",
  },
  {
    fullname: "Sarena Sapir",
    email: "ssapir1@quantcast.com",
    password: "K7lI5tml",
    shippingAddress: "425 Aberg Alley",
    phone: "732-407-2992",
  },
  {
    fullname: "Constantine Duncanson",
    email: "cduncanson2@merriam-webster.com",
    password: "815f16",
    shippingAddress: "217 Melvin Hill",
    phone: "998-181-2642",
  },
  {
    fullname: "Mr.Demo",
    email: "demo@gmail.com",
    password: "$2b$10$1RVAMssajUDlT1ejrw13COnkppuj4BaidguYcIo3knI41cXi/lAcm",
    shippingAddress: "4 Anthes Circle",
    phone: null,
  },
  {
    fullname: "Ruthi Shotter",
    email: "rshotter4@parallels.com",
    password: "3H5X3q",
    shippingAddress: "2640 Heath Center",
    phone: null,
  },
  {
    fullname: "Issie Patzelt",
    email: "ipatzelt5@answers.com",
    password: "l2AATT",
    shippingAddress: "2413 Glacier Hill Hill",
    phone: "123-658-2298",
  },
  {
    fullname: "Genevieve Aldam",
    email: "galdam6@amazonaws.com",
    password: "XLZu9vV",
    shippingAddress: "948 Almo Street",
    phone: "875-764-0070",
  },
  {
    fullname: "Lefty MacMichael",
    email: "lmacmichael7@newyorker.com",
    password: "ppzFSk0Df7Jt",
    shippingAddress: "3 Sachs Parkway",
    phone: "518-668-3711",
  },
  {
    fullname: "Imogene Ratray",
    email: "iratray8@washington.edu",
    password: "OwPJrMzC",
    shippingAddress: "6 Prairieview Avenue",
    phone: "730-197-7925",
  },
  {
    fullname: "Avrom Pyser",
    email: "apyser9@shareasale.com",
    password: "emmCrqghfW",
    shippingAddress: "697 Onsgard Terrace",
    phone: "303-887-9494",
  },
  // {
  //   fullname: "Colline Brekonridge",
  //   email: "cbrekonridgea@pen.io",
  //   password: "7gzYd6iaB6b",
  //   shippingAddress: "423 Mallard Hill",
  //   phone: "363-681-7069",
  // },
  // {
  //   fullname: "Gabriela Najafian",
  //   email: "gnajafianb@arizona.edu",
  //   password: "SGxkFu",
  //   shippingAddress: "8 Evergreen Pass",
  //   phone: "622-216-2898",
  // },
  // {
  //   fullname: "Kristos Bercevelo",
  //   email: "kberceveloc@ifeng.com",
  //   password: "moCOfmrI2TOi",
  //   shippingAddress: "71 Ronald Regan Drive",
  //   phone: "483-457-5724",
  // },
  // {
  //   fullname: "Gram Brambley",
  //   email: "gbrambleyd@yandex.ru",
  //   password: "VTHBnu7HM",
  //   shippingAddress: "7 Sunfield Drive",
  //   phone: "190-817-0898",
  // },
  // {
  //   fullname: "Oralee Maraga",
  //   email: "omaragae@ezinearticles.com",
  //   password: "P1qAZJlX",
  //   shippingAddress: "616 Comanche Way",
  //   phone: "348-610-1624",
  // },
  // {
  //   fullname: "Byrann Landers",
  //   email: "blandersf@nbcnews.com",
  //   password: "gqnFhD",
  //   shippingAddress: "36949 Northview Road",
  //   phone: "707-373-2159",
  // },
  // {
  //   fullname: "Ardenia Bogace",
  //   email: "abogaceg@freewebs.com",
  //   password: "6uSQVQU6",
  //   shippingAddress: "2282 Summer Ridge Alley",
  //   phone: "832-403-2512",
  // },
  // {
  //   fullname: "Sandi Nawton",
  //   email: "snawtonh@example.com",
  //   password: "OFMLsPr3",
  //   shippingAddress: "94 Hermina Terrace",
  //   phone: "414-323-4583",
  // },
  // {
  //   fullname: "Ernesto Lahiff",
  //   email: "elahiffi@archive.org",
  //   password: "y7BokP5uCb5",
  //   shippingAddress: "843 Manitowish Plaza",
  //   phone: "435-872-7447",
  // },
  // {
  //   fullname: "Gay Crutchfield",
  //   email: "gcrutchfieldj@mail.ru",
  //   password: "9SuZ8V",
  //   shippingAddress: "80993 Claremont Avenue",
  //   phone: "780-413-8249",
  // },
  // {
  //   fullname: "Elwira Benner",
  //   email: "ebennerk@eepurl.com",
  //   password: "p4bW1n",
  //   shippingAddress: "97601 Delladonna Parkway",
  //   phone: "973-108-0973",
  // },
  // {
  //   fullname: "Brandy Kellough",
  //   email: "bkelloughl@wordpress.com",
  //   password: "Jm50IO68j",
  //   shippingAddress: "87258 Grim Drive",
  //   phone: null,
  // },
  // {
  //   fullname: "Andie Upston",
  //   email: "aupstonm@vimeo.com",
  //   password: "XSNgBxDqYmtD",
  //   shippingAddress: "73892 Mccormick Plaza",
  //   phone: "177-984-7434",
  // },
  // {
  //   fullname: "Theadora Wyvill",
  //   email: "twyvilln@apple.com",
  //   password: "kZFVV2c1",
  //   shippingAddress: "6 Oriole Hill",
  //   phone: "521-123-0174",
  // },
  // {
  //   fullname: "Malynda Terrington",
  //   email: "mterringtono@angelfire.com",
  //   password: "Nq48Kce",
  //   shippingAddress: "7234 Bunting Drive",
  //   phone: "381-383-3553",
  // },
  // {
  //   fullname: "Nealon Rivlin",
  //   email: "nrivlinp@i2i.jp",
  //   password: "zl6G4kNZ",
  //   shippingAddress: "390 Granby Plaza",
  //   phone: "901-872-9353",
  // },
  // {
  //   fullname: "Corabel Tappin",
  //   email: "ctappinq@skyrock.com",
  //   password: "M1NotWEHA",
  //   shippingAddress: "75572 Scofield Park",
  //   phone: "295-672-5813",
  // },
  // {
  //   fullname: "Kelwin Gillinghams",
  //   email: "kgillinghamsr@canalblog.com",
  //   password: "9VDRzgi",
  //   shippingAddress: "64 Magdeline Terrace",
  //   phone: null,
  // },
  // {
  //   fullname: "Gabi Pace",
  //   email: "gpaces@home.pl",
  //   password: "JJhCje",
  //   shippingAddress: "9 Kipling Circle",
  //   phone: "172-601-5146",
  // },
  // {
  //   fullname: "Dominga Dufton",
  //   email: "dduftont@cocolog-nifty.com",
  //   password: "AsNO8m",
  //   shippingAddress: "0204 Carioca Plaza",
  //   phone: "395-265-7821",
  // },
  // {
  //   fullname: "Sandro Strathdee",
  //   email: "sstrathdeeu@acquirethisname.com",
  //   password: "L6Z9tkf",
  //   shippingAddress: "59 Mendota Avenue",
  //   phone: "284-478-8436",
  // },
  // {
  //   fullname: "Feodor Dabs",
  //   email: "fdabsv@zimbio.com",
  //   password: "nLFo0ULNSA",
  //   shippingAddress: "6 Boyd Circle",
  //   phone: "743-903-2217",
  // },
  // {
  //   fullname: "Albertina Keuntje",
  //   email: "akeuntjew@jigsy.com",
  //   password: "48ohzw8mQ",
  //   shippingAddress: "37015 Hoard Park",
  //   phone: "309-990-2908",
  // },
  // {
  //   fullname: "Mabelle Edghinn",
  //   email: "medghinnx@wix.com",
  //   password: "lwpdEqgX",
  //   shippingAddress: "254 Redwing Plaza",
  //   phone: null,
  // },
  // {
  //   fullname: "Dyanne Werner",
  //   email: "dwernery@shinystat.com",
  //   password: "zIi7qDIye",
  //   shippingAddress: "588 Mosinee Trail",
  //   phone: "229-584-6698",
  // },
  // {
  //   fullname: "Bethina Pigeon",
  //   email: "bpigeonz@wiley.com",
  //   password: "F0CO3E",
  //   shippingAddress: "73188 Ridgeview Street",
  //   phone: "101-513-7364",
  // },
  // {
  //   fullname: "Frankie Kurth",
  //   email: "fkurth10@creativecommons.org",
  //   password: "6TNZxxhXkAZU",
  //   shippingAddress: "4048 Twin Pines Park",
  //   phone: "588-979-5598",
  // },
  // {
  //   fullname: "Mady Duberry",
  //   email: "mduberry11@tumblr.com",
  //   password: "K3nEdJv0794",
  //   shippingAddress: "292 Elgar Road",
  //   phone: null,
  // },
  // {
  //   fullname: "King Anthoney",
  //   email: "kanthoney12@devhub.com",
  //   password: "vc2N8ZM4",
  //   shippingAddress: "4494 Myrtle Street",
  //   phone: null,
  // },
  // {
  //   fullname: "Brenn Winspire",
  //   email: "bwinspire13@toplist.cz",
  //   password: "WbjlDJhy7T",
  //   shippingAddress: "27 Norway Maple Road",
  //   phone: "193-515-0659",
  // },
  // {
  //   fullname: "Valerie Tretwell",
  //   email: "vtretwell14@purevolume.com",
  //   password: "6Pdwbk0xHS",
  //   shippingAddress: "0617 Dapin Street",
  //   phone: "869-175-7482",
  // },
  // {
  //   fullname: "Bernadina Nand",
  //   email: "bnand15@google.pl",
  //   password: "9AQ2uqO",
  //   shippingAddress: "954 Fremont Terrace",
  //   phone: "888-400-8510",
  // },
  // {
  //   fullname: "Mirabella Bakewell",
  //   email: "mbakewell16@simplemachines.org",
  //   password: "0Uc71Gwisb",
  //   shippingAddress: "4477 Straubel Way",
  //   phone: "502-904-5256",
  // },
  // {
  //   fullname: "Baldwin Longbottom",
  //   email: "blongbottom17@java.com",
  //   password: "joDOvK8Upgwv",
  //   shippingAddress: "43 Milwaukee Pass",
  //   phone: null,
  // },
  // {
  //   fullname: "Jerry Payne",
  //   email: "jpayne18@google.com.br",
  //   password: "oTIDxs0VG",
  //   shippingAddress: "67627 Truax Point",
  //   phone: "480-815-8259",
  // },
  // {
  //   fullname: "Lorilyn Coutthart",
  //   email: "lcoutthart19@google.de",
  //   password: "ixAIMdFYz",
  //   shippingAddress: "4 Aberg Court",
  //   phone: "439-532-5524",
  // },
  // {
  //   fullname: "Farica Chatwood",
  //   email: "fchatwood1a@indiatimes.com",
  //   password: "ywyzRBL",
  //   shippingAddress: "7 Schiller Circle",
  //   phone: "204-456-1357",
  // },
  // {
  //   fullname: "Marti Rodgers",
  //   email: "mrodgers1b@ucsd.edu",
  //   password: "KJthUi",
  //   shippingAddress: "2 Utah Trail",
  //   phone: "247-580-8714",
  // },
  // {
  //   fullname: "Ariel Moryson",
  //   email: "amoryson1c@vk.com",
  //   password: "T4qrpd2",
  //   shippingAddress: "2600 Garrison Avenue",
  //   phone: "385-843-9092",
  // },
  // {
  //   fullname: "Fidole Cordey",
  //   email: "fcordey1d@meetup.com",
  //   password: "bp4bLthvZl2G",
  //   shippingAddress: "08 Nelson Park",
  //   phone: "215-900-6544",
  // },
  // {
  //   fullname: "Nye Twitching",
  //   email: "ntwitching1e@canalblog.com",
  //   password: "LkrUs64RAla1",
  //   shippingAddress: "05844 Spenser Place",
  //   phone: "725-242-7882",
  // },
  // {
  //   fullname: "Gifford Blesdill",
  //   email: "gblesdill1f@angelfire.com",
  //   password: "U5yPynAxYZdj",
  //   shippingAddress: "6297 Corry Parkway",
  //   phone: "260-377-0196",
  // },
  // {
  //   fullname: "Aviva Conradsen",
  //   email: "aconradsen1g@imgur.com",
  //   password: "jTdtI1wcj",
  //   shippingAddress: "7794 Jay Plaza",
  //   phone: "958-598-9675",
  // },
  // {
  //   fullname: "Roxanne Tremayle",
  //   email: "rtremayle1h@blogger.com",
  //   password: "irJXr0nM",
  //   shippingAddress: "7448 Schlimgen Park",
  //   phone: null,
  // },
  // {
  //   fullname: "Debra Beeble",
  //   email: "dbeeble1i@sogou.com",
  //   password: "Iric7s3FGHlb",
  //   shippingAddress: "44 Messerschmidt Center",
  //   phone: "122-928-9106",
  // },
  // {
  //   fullname: "Morgana Bulfoy",
  //   email: "mbulfoy1j@icio.us",
  //   password: "pYBtmjAUz",
  //   shippingAddress: "84 Hazelcrest Plaza",
  //   phone: null,
  // },
  // {
  //   fullname: "Haydon Brundall",
  //   email: "hbrundall1k@slideshare.net",
  //   password: "UHS7LUR",
  //   shippingAddress: "48930 Fairfield Way",
  //   phone: "464-470-1491",
  // },
  // {
  //   fullname: "Bancroft Trenfield",
  //   email: "btrenfield1l@usatoday.com",
  //   password: "UCiwngytJ9h",
  //   shippingAddress: "5 Lakewood Gardens Alley",
  //   phone: null,
  // },
  // {
  //   fullname: "Baxy Pinchback",
  //   email: "bpinchback1m@shareasale.com",
  //   password: "PDxNvfSueICN",
  //   shippingAddress: "30 Sommers Drive",
  //   phone: "615-334-9383",
  // },
  // {
  //   fullname: "Katie Beams",
  //   email: "kbeams1n@flickr.com",
  //   password: "PBsL5UW",
  //   shippingAddress: "023 American Road",
  //   phone: "650-707-3614",
  // },
  // {
  //   fullname: "Othello McLugaish",
  //   email: "omclugaish1o@jimdo.com",
  //   password: "UhlinSc5lL",
  //   shippingAddress: "6505 Bellgrove Street",
  //   phone: "514-608-3822",
  // },
  // {
  //   fullname: "Wilbert Presnall",
  //   email: "wpresnall1p@princeton.edu",
  //   password: "2jcOu4b",
  //   shippingAddress: "638 Shoshone Junction",
  //   phone: "806-978-0679",
  // },
  // {
  //   fullname: "Dehlia Pulver",
  //   email: "dpulver1q@sina.com.cn",
  //   password: "OWdHPnJlPQ",
  //   shippingAddress: "75722 Caliangt Trail",
  //   phone: "632-843-4692",
  // },
  // {
  //   fullname: "Marlon Brazenor",
  //   email: "mbrazenor1r@plala.or.jp",
  //   password: "5lYWVQ",
  //   shippingAddress: "2076 Anniversary Way",
  //   phone: null,
  // },
  // {
  //   fullname: "Shanon Farmery",
  //   email: "sfarmery1s@census.gov",
  //   password: "NhOKnxA",
  //   shippingAddress: "5318 Westend Hill",
  //   phone: "921-457-5351",
  // },
  // {
  //   fullname: "Lizette Gilvear",
  //   email: "lgilvear1t@cbc.ca",
  //   password: "faDbAMn2y",
  //   shippingAddress: "29 Arizona Avenue",
  //   phone: null,
  // },
  // {
  //   fullname: "Westley Babonau",
  //   email: "wbabonau1u@tamu.edu",
  //   password: "tVALUnN2wY",
  //   shippingAddress: "4311 La Follette Place",
  //   phone: "486-343-2959",
  // },
  // {
  //   fullname: "Honor Stainbridge",
  //   email: "hstainbridge1v@reverbnation.com",
  //   password: "yhJv7hN",
  //   shippingAddress: "0517 Manitowish Road",
  //   phone: "371-216-6833",
  // },
  // {
  //   fullname: "Kristin Dunkerton",
  //   email: "kdunkerton1w@ezinearticles.com",
  //   password: "Ui0G3rM",
  //   shippingAddress: "530 Stang Junction",
  //   phone: "465-965-4012",
  // },
  // {
  //   fullname: "Bonnie Grelka",
  //   email: "bgrelka1x@jalbum.net",
  //   password: "QA4OWDKh",
  //   shippingAddress: "7656 Reindahl Hill",
  //   phone: "463-646-5901",
  // },
  // {
  //   fullname: "Hurley Slocomb",
  //   email: "hslocomb1y@weebly.com",
  //   password: "YFkb5IsW4MX",
  //   shippingAddress: "9155 Pond Circle",
  //   phone: "440-915-4747",
  // },
  // {
  //   fullname: "Dahlia Fall",
  //   email: "dfall1z@ox.ac.uk",
  //   password: "0kenNEU",
  //   shippingAddress: "61317 Tennyson Point",
  //   phone: "254-578-9016",
  // },
  // {
  //   fullname: "Heywood Crocker",
  //   email: "hcrocker20@mysql.com",
  //   password: "0TKgqzgAbi",
  //   shippingAddress: "0585 Old Gate Court",
  //   phone: null,
  // },
  // {
  //   fullname: "Connor Ridsdale",
  //   email: "cridsdale21@hibu.com",
  //   password: "CZz4TLHOojnm",
  //   shippingAddress: "64 Pankratz Pass",
  //   phone: "874-328-3081",
  // },
  // {
  //   fullname: "Ynes Parradice",
  //   email: "yparradice22@loc.gov",
  //   password: "psbDgKKgJLKw",
  //   shippingAddress: "12370 Killdeer Drive",
  //   phone: null,
  // },
  // {
  //   fullname: "Kaila Kirvell",
  //   email: "kkirvell23@ovh.net",
  //   password: "Py6qJGlSZX",
  //   shippingAddress: "206 Hanson Plaza",
  //   phone: null,
  // },
  // {
  //   fullname: "Zorana Friese",
  //   email: "zfriese24@walmart.com",
  //   password: "cZCppJyInB",
  //   shippingAddress: "18 Stang Avenue",
  //   phone: "648-344-1378",
  // },
  // {
  //   fullname: "Judon Charpling",
  //   email: "jcharpling25@netscape.com",
  //   password: "o5IgW9uI",
  //   shippingAddress: "22653 Pleasure Point",
  //   phone: "229-458-9886",
  // },
  // {
  //   fullname: "Niki Ewers",
  //   email: "newers26@mozilla.com",
  //   password: "tbdcrg5",
  //   shippingAddress: "581 La Follette Plaza",
  //   phone: "330-369-6546",
  // },
  // {
  //   fullname: "Hobie Surtees",
  //   email: "hsurtees27@yale.edu",
  //   password: "jkYhwc4fCm",
  //   shippingAddress: "21 Spohn Circle",
  //   phone: "117-882-1906",
  // },
  // {
  //   fullname: "Gray Weiser",
  //   email: "gweiser28@stanford.edu",
  //   password: "aos8tsw",
  //   shippingAddress: "10 Lyons Point",
  //   phone: "993-162-2172",
  // },
  // {
  //   fullname: "Jojo Graber",
  //   email: "jgraber29@surveymonkey.com",
  //   password: "CQVCnNnq",
  //   shippingAddress: "44343 Maryland Terrace",
  //   phone: null,
  // },
  // {
  //   fullname: "Mervin Kalker",
  //   email: "mkalker2a@usatoday.com",
  //   password: "qe0w14",
  //   shippingAddress: "00 Arizona Place",
  //   phone: null,
  // },
  // {
  //   fullname: "Gilburt Verriour",
  //   email: "gverriour2b@webmd.com",
  //   password: "1UgW0ic",
  //   shippingAddress: "8 Burrows Lane",
  //   phone: "623-487-6196",
  // },
  // {
  //   fullname: "Selinda Hendrich",
  //   email: "shendrich2c@prlog.org",
  //   password: "JlUe7PmqK8",
  //   shippingAddress: "83158 Mandrake Trail",
  //   phone: "653-192-6462",
  // },
  // {
  //   fullname: "Leonore Scothorn",
  //   email: "lscothorn2d@myspace.com",
  //   password: "sOQpKnYpW6o",
  //   shippingAddress: "93690 Muir Drive",
  //   phone: null,
  // },
  // {
  //   fullname: "Isidro Etoile",
  //   email: "ietoile2e@statcounter.com",
  //   password: "YQOAilhmH1I",
  //   shippingAddress: "42164 Bartelt Alley",
  //   phone: "215-742-8720",
  // },
  // {
  //   fullname: "Cacilia Hancock",
  //   email: "chancock2f@vimeo.com",
  //   password: "33wBIdymZR",
  //   shippingAddress: "0 Cardinal Place",
  //   phone: "624-695-9116",
  // },
  // {
  //   fullname: "Hans Ballintyne",
  //   email: "hballintyne2g@addthis.com",
  //   password: "1FTLddlh",
  //   shippingAddress: "1 Sutteridge Lane",
  //   phone: "609-994-0833",
  // },
  // {
  //   fullname: "Crista Murray",
  //   email: "cmurray2h@epa.gov",
  //   password: "ox8sbZtjDE",
  //   shippingAddress: "7 Spenser Street",
  //   phone: "165-597-6521",
  // },
  // {
  //   fullname: "Joan Codling",
  //   email: "jcodling2i@miitbeian.gov.cn",
  //   password: "E6fPAaaBrFF5",
  //   shippingAddress: "8 Jana Court",
  //   phone: "705-544-5281",
  // },
  // {
  //   fullname: "Hadrian Frankish",
  //   email: "hfrankish2j@naver.com",
  //   password: "ujNTeMEPt",
  //   shippingAddress: "39154 Ohio Alley",
  //   phone: "716-783-8373",
  // },
  // {
  //   fullname: "Luciano Crocombe",
  //   email: "lcrocombe2k@simplemachines.org",
  //   password: "sWBerYyS",
  //   shippingAddress: "47438 Eagan Crossing",
  //   phone: "715-583-3039",
  // },
  // {
  //   fullname: "Westley Jerzyk",
  //   email: "wjerzyk2l@google.ca",
  //   password: "46uTsSqvRg",
  //   shippingAddress: "2 Oxford Court",
  //   phone: "790-505-6013",
  // },
  // {
  //   fullname: "Dorisa Chanter",
  //   email: "dchanter2m@symantec.com",
  //   password: "t0ixwXVkT",
  //   shippingAddress: "99 Graedel Crossing",
  //   phone: "727-665-0711",
  // },
  // {
  //   fullname: "Ruperta Scrooby",
  //   email: "rscrooby2n@multiply.com",
  //   password: "Bepg8wMsd",
  //   shippingAddress: "9 Helena Parkway",
  //   phone: "647-671-4262",
  // },
  // {
  //   fullname: "Des Tewkesberry",
  //   email: "dtewkesberry2o@comcast.net",
  //   password: "RCRI7u5Y",
  //   shippingAddress: "51 Declaration Alley",
  //   phone: "704-799-4221",
  // },
  // {
  //   fullname: "Gannon McPheat",
  //   email: "gmcpheat2p@scribd.com",
  //   password: "7bGzHUK",
  //   shippingAddress: "6 Express Place",
  //   phone: "780-848-0691",
  // },
  // {
  //   fullname: "Emera Bumphrey",
  //   email: "ebumphrey2q@china.com.cn",
  //   password: "j6ubcQgU",
  //   shippingAddress: "1261 Ridge Oak Road",
  //   phone: "188-448-5511",
  // },
  // {
  //   fullname: "Graehme Chastand",
  //   email: "gchastand2r@redcross.org",
  //   password: "Y1I6cM",
  //   shippingAddress: "88 Nova Drive",
  //   phone: "777-676-6234",
  // },
];

export const admins: {
  username: string;
  email: string;
  password: string;
  role: Role;
}[] = [
  {
    username: "superadmin",
    email: "superadmin@gmail.com",
    password: "$2b$10$89O/57zd05yMYmkT4JJqhekHY7W0rtTVYpsrgohbZYcdOIouMFB2O",
    role: "SUPERADMIN",
  },
  {
    username: "admin",
    email: "admin@gmail.com",
    password: "$2b$10$4sLZXBrPa4Hm4Mde3OJ0GesAgyhhmglcpOfNCQ8K6/5GIJbAfbWMO",
    role: "ADMIN",
  },
  {
    username: "mod",
    email: "mod@gmail.com",
    password: "$2b$10$pDf2Qjhh2WilM8pN7r44zuodGA3zoFN/Zu8CCAI0pwQXkUR.okT/a",
    role: "MODERATOR",
  },
];

// Category Data (3)
export const categories = [
  {
    name: "men",
    description: "sapien non mi integer ac neque duis bibendum morbi non",
    thumbnailImage: "http://dummyimage.com/720x400.png/cc0000/ffffff",
  },
  {
    name: "women",
    description:
      "eget vulputate ut ultrices vel augue vestibulum ante ipsum primis",
    thumbnailImage: "http://dummyimage.com/720x400.png/dddddd/000000",
  },
  {
    name: "bags",
    description:
      "turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh",
    thumbnailImage: "http://dummyimage.com/720x400.png/dddddd/000000",
  },
  // {
  //   name: "Toughjoyfax",
  //   description:
  //     "odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis",
  //   thumbnailImage: "http://dummyimage.com/720x400.png/cc0000/ffffff",
  // },
  // {
  //   name: "Konklab",
  //   description:
  //     "in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit",
  //   thumbnailImage: "http://dummyimage.com/720x400.png/dddddd/000000",
  // },
];



// Products Data (100)
export const products = [
  {
    name: "Aerified",
    description:
      "condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros",
    detail:
      "mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum",
    categoryId: 1,
  },
];

export const proOptions = [
  {
    color: "#cAcAca",
    price: 100,
    size: "M,L",
    stock: 23,
    images: "http://dummyimage.com/720x400.png/cc0000/ffffff",
    productId: 1,
  },
];