-- AlterTable
ALTER TABLE "proOptions" ALTER COLUMN "color" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "size" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "images" SET DATA TYPE VARCHAR(500);

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "name" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(500);
